{% set name = "algorithms" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/algorithms-{{ version }}.tar.gz
  sha256: ccd05e13d4ad169b0061028b16b16e7f67e884d237a8bbff13b354ee5d31f34c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - algorithms
    - algorithms.arrays
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/keon/algorithms
  summary: Pythonic Data Structures and Algorithms
  license: MIT
  license_file: LICENSE
  description: |
    Minimal and clean example implementations of data structures and algorithms
     in Python 3.

extra:
  recipe-maintainers:
    - thewchan
